name: Dependency Protection

on:
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.npmrc'
  pull_request:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - '.npmrc'
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  check-package-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Verify .npmrc configuration
        run: |
          if [ ! -f .npmrc ]; then
            echo "::error::.npmrc file not found. This file is required for dependency protection."
            exit 1
          fi
          
          if ! grep -q "@jordanjackson:registry=" .npmrc; then
            echo "::error::No scoped registry configuration found in .npmrc. This is required for dependency protection."
            exit 1
          fi
          
          if ! grep -q "registry=https://registry.npmjs.org/" .npmrc; then
            echo "::warning::No default registry specified in .npmrc. This is recommended for dependency protection."
          fi
          
          echo "✅ .npmrc configuration verified"

  check-package-names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Verify package name
        run: |
          pkg_name=$(node -p "require('./package.json').name")
          if [[ $pkg_name != @* ]]; then
            echo "::error::Package name is not scoped (@organization/name). This is required for dependency protection."
            exit 1
          else
            echo "✅ Package name is properly scoped: $pkg_name"
          fi
          
      - name: Check for potential namespace conflicts
        run: |
          pkg_scope=$(node -p "require('./package.json').name.split('/')[0]")
          echo "Checking for potential namespace conflicts with $pkg_scope..."
          
          # Query npm to see if the scope exists
          if curl -s "https://registry.npmjs.org/-/user/org.couchdb.user:${pkg_scope#@}" | grep -q "error"; then
            echo "✅ No existing npm organization found with the same name"
          else
            echo "::warning::An npm organization with the name $pkg_scope already exists. Verify this is your organization."
          fi

  prevent-dependency-confusion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run dependency confusion check
        run: node scripts/security-check.js
        
      - name: Generate report
        run: |
          echo "# Dependency Protection Report" > dependency-report.md
          echo "Generated at: $(date)" >> dependency-report.md
          echo "" >> dependency-report.md
          echo "## Package Information" >> dependency-report.md
          echo "- Name: $(node -p "require('./package.json').name")" >> dependency-report.md
          echo "- Version: $(node -p "require('./package.json').version")" >> dependency-report.md
          echo "" >> dependency-report.md
          echo "## Registry Configuration" >> dependency-report.md
          if [ -f .npmrc ]; then
            echo "✅ .npmrc file exists" >> dependency-report.md
            if grep -q "@jordanjackson:registry=" .npmrc; then
              echo "✅ Scope registry configuration exists" >> dependency-report.md
            else
              echo "❌ No scope registry configuration found" >> dependency-report.md
            fi
          else
            echo "❌ No .npmrc file found" >> dependency-report.md
          fi
          
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-protection-report
          path: dependency-report.md
          retention-days: 30 